version: '3.8'
services:
  api_run:
    build:
      context: ./api  # Path to the directory containing the Dockerfile for api_run.py
    command: python api_call.py
    volumes:
      - ./api:/app  # Mount the api directory to /app in the container
    ports:
      - "7000:7000"

  app:
    build:
      context: .  # Path to the directory containing the Dockerfile for app.py
    command: python app.py
    volumes:
      - .:/app  # Mount the root directory to /app in the container
    ports:
      - "5000:5000"
    depends_on:
      - api_run